package abi

// x86_64 mnemonic constants used across abi analyzers
const (
	mnemonicCall = "call"
	mnemonicRet  = "ret"
	mnemonicRetn = "retn"
	mnemonicPush = "push"
	mnemonicPop  = "pop"
	mnemonicMov  = "mov"
	mnemonicSub  = "sub"
	mnemonicAdd  = "add"
	mnemonicAnd  = "and"
	mnemonicTest = "test"
	mnemonicCmp  = "cmp"
)

// x86_64 register name constants used across abi analyzers
const (
	regRax  = "rax"
	regRbx  = "rbx"
	regRcx  = "rcx"
	regRdx  = "rdx"
	regRsi  = "rsi"
	regRdi  = "rdi"
	regRbp  = "rbp"
	regRsp  = "rsp"
	regR10  = "r10"
	regR11  = "r11"
	regR12  = "r12"
	regR13  = "r13"
	regR14  = "r14"
	regR15  = "r15"
	regXmm0 = "xmm0"
	regXmm1 = "xmm1"
	regXmm2 = "xmm2"
	regXmm3 = "xmm3"
	regXmm4 = "xmm4"
	regXmm5 = "xmm5"
	regXmm6 = "xmm6"
	regXmm7 = "xmm7"
)

// sub-register alias constants shared between registers.go and register_width.go
const (
	subregEax  = "eax"
	subregEbx  = "ebx"
	subregEcx  = "ecx"
	subregEdx  = "edx"
	subregEsi  = "esi"
	subregEdi  = "edi"
	subregEbp  = "ebp"
	subregEsp  = "esp"
	subregBpl  = "bpl"
	subregSpl  = "spl"
	subregSil  = "sil"
	subregDil  = "dil"
	subregR8d  = "r8d"
	subregR8w  = "r8w"
	subregR8b  = "r8b"
	subregR9d  = "r9d"
	subregR9w  = "r9w"
	subregR9b  = "r9b"
	subregR10d = "r10d"
	subregR10w = "r10w"
	subregR10b = "r10b"
	subregR11d = "r11d"
	subregR11w = "r11w"
	subregR11b = "r11b"
	subregR12d = "r12d"
	subregR12w = "r12w"
	subregR12b = "r12b"
	subregR13d = "r13d"
	subregR13w = "r13w"
	subregR13b = "r13b"
	subregR14d = "r14d"
	subregR14w = "r14w"
	subregR14b = "r14b"
	subregR15d = "r15d"
	subregR15w = "r15w"
	subregR15b = "r15b"
)
