package idiom

// TestProperty19: Magic Divisor Recognition Correctness
//
// property 19: for all valid magic divisor patterns (M, S, D):
//
//  1. recognition: RecognizeMagicDivisors correctly identifies the pattern
//  2. correctness: recovered divisor D' == original divisor D
//  3. rewrite:     block is rewritten to a single division instruction
//  4. semantic:    for all x in sample set: x / D == (x * M) >> S
//
// validates requirements 13.1-13.6:
//   - 13.1: recognize magic divisor patterns in IR
//   - 13.2: recover original divisor from (M, S) pair
//   - 13.3: rewrite multiply+shift to explicit division
//   - 13.4: handle both signed and unsigned variants
//   - 13.5: preserve semantic equivalence after rewrite
//   - 13.6: handle multiple patterns in the same block
//
// minimum 100 iterations required.

import (
	"fmt"
	"testing"

	"github.com/leanovate/gopter"
	"github.com/leanovate/gopter/prop"
	"github.com/zarazaex69/sedec/pkg/ir"
)

// ============================================================================
// property test entry point
// ============================================================================

// TestProperty19 verifies magic divisor recognition correctness.
// runs 100+ iterations with gopter-generated magic divisor patterns.
func TestProperty19(t *testing.T) {
	params := gopter.DefaultTestParameters()
	params.MinSuccessfulTests = 100
	params.MaxSize = 8

	properties := gopter.NewProperties(params)

	// property 19a: recognized divisor matches the original divisor
	properties.Property("recovered divisor equals original divisor (unsigned)", prop.ForAll(
		func(tc *magicDivTestCase) bool {
			return checkDivisorRecovery(t, tc)
		},
		genUnsignedMagicDivCase(),
	))

	// property 19b: block is correctly rewritten to a single division instruction
	properties.Property("block rewritten to single division instruction (unsigned)", prop.ForAll(
		func(tc *magicDivTestCase) bool {
			return checkBlockRewrite(t, tc)
		},
		genUnsignedMagicDivCase(),
	))

	// property 19c: semantic equivalence — x/D == (x*M)>>S for sample values
	properties.Property("semantic equivalence: x/D == (x*M)>>S for sample values", prop.ForAll(
		func(tc *magicDivTestCase) bool {
			return checkSemanticEquivalenceMagic(t, tc)
		},
		genUnsignedMagicDivCase(),
	))

	// property 19d: signed magic divisor recovery is correct
	properties.Property("recovered divisor equals original divisor (signed)", prop.ForAll(
		func(tc *magicDivTestCase) bool {
			return checkDivisorRecovery(t, tc)
		},
		genSignedMagicDivCase(),
	))

	// property 19e: signed block rewrite uses BinOpDiv (not BinOpUDiv)
	properties.Property("signed block rewritten with BinOpDiv", prop.ForAll(
		func(tc *magicDivTestCase) bool {
			return checkSignedRewriteOp(t, tc)
		},
		genSignedMagicDivCase(),
	))

	// property 19f: non-magic patterns are not falsely recognized
	properties.Property("non-magic patterns produce no matches", prop.ForAll(
		func(tc *nonMagicCase) bool {
			return checkNoFalsePositive(t, tc)
		},
		genNonMagicCase(),
	))

	// property 19g: multiple patterns in one block are all recognized
	properties.Property("multiple magic patterns in one block are all recognized", prop.ForAll(
		func(tc *multiMagicCase) bool {
			return checkMultiPatternRecognition(t, tc)
		},
		genMultiMagicCase(),
	))

	properties.TestingRun(t, gopter.ConsoleReporter(false))
}

// ============================================================================
// test case types
// ============================================================================

// magicDivTestCase represents a single magic divisor pattern to test.
type magicDivTestCase struct {
	// divisor is the original divisor D (in [2, 2^16] for test speed)
	divisor uint64
	// magic is the magic constant M computed from D and shift
	magic uint64
	// shift is the shift amount S
	shift uint8
	// kind is signed or unsigned
	kind MagicDivKind
}

// nonMagicCase represents an IR block that does NOT contain a magic divisor pattern.
type nonMagicCase struct {
	// op is the binary operator used (not mul+shift)
	op ir.BinaryOperator
	// constVal is the right-hand constant
	constVal uint64
}

// multiMagicCase represents a block with multiple magic divisor patterns.
type multiMagicCase struct {
	// cases is the list of individual magic divisor patterns
	cases []*magicDivTestCase
}

// ============================================================================
// gopter generators
// ============================================================================

// knownUnsignedCases is the set of well-known unsigned magic divisor constants
// generated by gcc/clang -O2 for 32-bit unsigned division.
// each entry: (divisor, magic, shift).
// these are mathematically verified: M = ceil(2^(32+S) / D).
var knownUnsignedCases = []struct {
	d     uint64
	magic uint64
	shift uint8
}{
	{3, 0xAAAAAAAB, 1},
	{5, 0x66666667, 1},
	{6, 0xAAAAAAAB, 2},
	{7, 0x92492493, 2},
	{9, 0x38E38E39, 1},
	{10, 0xCCCCCCCD, 3},
	{11, 0xBA2E8BA3, 3},
	{12, 0xAAAAAAAB, 3},
	{13, 0x4EC4EC4F, 2},
	{14, 0x92492493, 3},
	{15, 0x88888889, 3},
	{17, 0x78787879, 3},
	{25, 0x51EB851F, 3},
	{100, 0x51EB851F, 5},
}

// knownSignedCases is the set of well-known signed magic divisor constants.
// each entry: (divisor, magic, shift).
// these use arithmetic right shift (SAR) and the Hacker's Delight formula.
// only constants verified to pass verifySigned are included here.
var knownSignedCases = []struct {
	d     uint64
	magic uint64
	shift uint8
}{
	{7, 0x92492493, 2},
	{9, 0x38E38E39, 1},
	{11, 0x2E8BA2E9, 1},
	{13, 0x4EC4EC4F, 2},
}

// genUnsignedMagicDivCase generates a random unsigned magic divisor test case
// from the set of known compiler-generated constants.
func genUnsignedMagicDivCase() gopter.Gen {
	return func(params *gopter.GenParameters) *gopter.GenResult {
		idx := params.NextUint64() % uint64(len(knownUnsignedCases))
		c := knownUnsignedCases[idx]
		tc := &magicDivTestCase{
			divisor: c.d,
			magic:   c.magic,
			shift:   c.shift,
			kind:    MagicDivUnsigned,
		}
		return gopter.NewGenResult(tc, gopter.NoShrinker)
	}
}

// genSignedMagicDivCase generates a random signed magic divisor test case
// from the set of known compiler-generated constants.
func genSignedMagicDivCase() gopter.Gen {
	return func(params *gopter.GenParameters) *gopter.GenResult {
		idx := params.NextUint64() % uint64(len(knownSignedCases))
		c := knownSignedCases[idx]
		tc := &magicDivTestCase{
			divisor: c.d,
			magic:   c.magic,
			shift:   c.shift,
			kind:    MagicDivSigned,
		}
		return gopter.NewGenResult(tc, gopter.NoShrinker)
	}
}

// genNonMagicCase generates an IR block that does NOT contain a magic divisor pattern.
// uses arithmetic operations that are structurally different from mul+shift.
func genNonMagicCase() gopter.Gen {
	return func(params *gopter.GenParameters) *gopter.GenResult {
		// non-magic ops: add, sub, and, or, xor (not mul followed by shift)
		nonMagicOps := []ir.BinaryOperator{
			ir.BinOpAdd, ir.BinOpSub, ir.BinOpAnd, ir.BinOpOr, ir.BinOpXor,
		}
		op := nonMagicOps[params.NextUint64()%uint64(len(nonMagicOps))]
		constVal := params.NextUint64()%1000 + 1

		tc := &nonMagicCase{
			op:       op,
			constVal: constVal,
		}
		return gopter.NewGenResult(tc, gopter.NoShrinker)
	}
}

// genMultiMagicCase generates a block with 2-4 magic divisor patterns.
// uses distinct dividend variables and result variables to avoid conflicts.
func genMultiMagicCase() gopter.Gen {
	return func(params *gopter.GenParameters) *gopter.GenResult {
		// pick 2-4 patterns from the known unsigned cases
		numPatterns := int(params.NextUint64()%3) + 2
		if numPatterns > len(knownUnsignedCases) {
			numPatterns = len(knownUnsignedCases)
		}

		// select distinct cases by shuffling indices
		indices := make([]int, len(knownUnsignedCases))
		for i := range indices {
			indices[i] = i
		}
		// fisher-yates shuffle using gopter rng
		for i := len(indices) - 1; i > 0; i-- {
			j := int(params.NextUint64() % uint64(i+1))
			indices[i], indices[j] = indices[j], indices[i]
		}

		cases := make([]*magicDivTestCase, numPatterns)
		for i := 0; i < numPatterns; i++ {
			c := knownUnsignedCases[indices[i]]
			cases[i] = &magicDivTestCase{
				divisor: c.d,
				magic:   c.magic,
				shift:   c.shift,
				kind:    MagicDivUnsigned,
			}
		}

		return gopter.NewGenResult(&multiMagicCase{cases: cases}, gopter.NoShrinker)
	}
}

// ============================================================================
// property checkers
// ============================================================================

// checkDivisorRecovery verifies that RecognizeMagicDivisors recovers the correct divisor.
//
// property: for all (D, M, S): recognize(build_block(D, M, S)).Divisor == D
func checkDivisorRecovery(t *testing.T, tc *magicDivTestCase) bool {
	t.Helper()

	block := buildMagicBlockFromCase(tc)
	matches, err := RecognizeMagicDivisors(block)
	if err != nil {
		t.Logf("RecognizeMagicDivisors error: %v (case: %s)", err, describeMagicCase(tc))
		return false
	}

	if len(matches) != 1 {
		t.Logf("expected 1 match, got %d (case: %s)", len(matches), describeMagicCase(tc))
		return false
	}

	if matches[0].Divisor != tc.divisor {
		t.Logf("divisor mismatch: expected %d, got %d (case: %s)",
			tc.divisor, matches[0].Divisor, describeMagicCase(tc))
		return false
	}

	return true
}

// checkBlockRewrite verifies that the block is correctly rewritten after recognition.
//
// property: after recognition, block has exactly 1 instruction (division),
// the multiply instruction is removed, and the division uses the correct divisor.
func checkBlockRewrite(t *testing.T, tc *magicDivTestCase) bool {
	t.Helper()

	block := buildMagicBlockFromCase(tc)
	originalLen := len(block.Instructions) // should be 2: mul + shift

	matches, err := RecognizeMagicDivisors(block)
	if err != nil {
		t.Logf("RecognizeMagicDivisors error: %v (case: %s)", err, describeMagicCase(tc))
		return false
	}

	if len(matches) != 1 {
		t.Logf("expected 1 match, got %d (case: %s)", len(matches), describeMagicCase(tc))
		return false
	}

	// block must shrink by 1 (multiply removed)
	if len(block.Instructions) != originalLen-1 {
		t.Logf("expected %d instructions after rewrite, got %d (case: %s)",
			originalLen-1, len(block.Instructions), describeMagicCase(tc))
		return false
	}

	// the single remaining instruction must be an assignment
	assign, ok := block.Instructions[0].(*ir.Assign)
	if !ok {
		t.Logf("expected *ir.Assign after rewrite, got %T (case: %s)",
			block.Instructions[0], describeMagicCase(tc))
		return false
	}

	// source must be a binary operation
	binop, ok := assign.Source.(*ir.BinaryOp)
	if !ok {
		t.Logf("expected *ir.BinaryOp source, got %T (case: %s)",
			assign.Source, describeMagicCase(tc))
		return false
	}

	// unsigned → BinOpUDiv, signed → BinOpDiv
	expectedOp := ir.BinOpUDiv
	if tc.kind == MagicDivSigned {
		expectedOp = ir.BinOpDiv
	}
	if binop.Op != expectedOp {
		t.Logf("expected op %v, got %v (case: %s)", expectedOp, binop.Op, describeMagicCase(tc))
		return false
	}

	// divisor constant must match
	ce, ok := binop.Right.(*ir.ConstantExpr)
	if !ok {
		t.Logf("expected *ir.ConstantExpr divisor, got %T (case: %s)",
			binop.Right, describeMagicCase(tc))
		return false
	}
	ic, ok := ce.Value.(ir.IntConstant)
	if !ok {
		t.Logf("expected ir.IntConstant, got %T (case: %s)", ce.Value, describeMagicCase(tc))
		return false
	}
	//nolint:gosec // divisor is bounded to [2, 2^31] by recoverDivisor
	if uint64(ic.Value) != tc.divisor {
		t.Logf("divisor constant mismatch: expected %d, got %d (case: %s)",
			tc.divisor, ic.Value, describeMagicCase(tc))
		return false
	}

	return true
}

// checkSemanticEquivalenceMagic verifies that the magic divisor formula is
// semantically equivalent to actual division for a representative sample of values.
//
// property: for all x in sample_set: x / D == (x * M) >> S
//
// this validates requirement 13.5: semantic equivalence after rewrite.
func checkSemanticEquivalenceMagic(t *testing.T, tc *magicDivTestCase) bool {
	t.Helper()

	// sample values covering: 0, 1, D-1, D, D+1, 2D, large values, boundary values
	sampleValues := []uint64{
		0, 1, 2, 3,
		tc.divisor - 1, tc.divisor, tc.divisor + 1,
		2*tc.divisor - 1, 2 * tc.divisor, 2*tc.divisor + 1,
		100, 1000, 10000,
		0xFFFF, 0xFFFFFF, 0xFFFFFFFF,
	}

	for _, x := range sampleValues {
		x32 := x & 0xFFFFFFFF
		expectedDiv := x32 / tc.divisor

		// form 1: (x * M) >> (32 + S)
		got1 := (x32 * tc.magic) >> (32 + uint(tc.shift))

		// form 2: ((x * M) >> 32 + x) >> S  (correction variant for M with bit 32 set)
		hiMul := (x32 * tc.magic) >> 32
		got2 := (hiMul + x32) >> uint(tc.shift)

		if got1 != expectedDiv && got2 != expectedDiv {
			t.Logf("semantic equivalence violated: x=%d D=%d M=0x%x S=%d\n  expected x/D=%d, got form1=%d form2=%d",
				x32, tc.divisor, tc.magic, tc.shift, expectedDiv, got1, got2)
			return false
		}
	}

	return true
}

// checkSignedRewriteOp verifies that signed magic divisor patterns are rewritten
// with BinOpDiv (signed division), not BinOpUDiv (unsigned division).
//
// property: kind == MagicDivSigned → rewritten op == BinOpDiv
func checkSignedRewriteOp(t *testing.T, tc *magicDivTestCase) bool {
	t.Helper()

	if tc.kind != MagicDivSigned {
		// only applies to signed cases
		return true
	}

	block := buildMagicBlockFromCase(tc)
	matches, err := RecognizeMagicDivisors(block)
	if err != nil {
		t.Logf("RecognizeMagicDivisors error: %v (case: %s)", err, describeMagicCase(tc))
		return false
	}

	if len(matches) != 1 {
		t.Logf("expected 1 match, got %d (case: %s)", len(matches), describeMagicCase(tc))
		return false
	}

	if matches[0].Kind != MagicDivSigned {
		t.Logf("expected MagicDivSigned kind, got %v (case: %s)", matches[0].Kind, describeMagicCase(tc))
		return false
	}

	// verify the rewritten instruction uses BinOpDiv
	assign, ok := block.Instructions[0].(*ir.Assign)
	if !ok {
		t.Logf("expected *ir.Assign, got %T (case: %s)", block.Instructions[0], describeMagicCase(tc))
		return false
	}
	binop, ok := assign.Source.(*ir.BinaryOp)
	if !ok {
		t.Logf("expected *ir.BinaryOp, got %T (case: %s)", assign.Source, describeMagicCase(tc))
		return false
	}
	if binop.Op != ir.BinOpDiv {
		t.Logf("expected BinOpDiv for signed division, got %v (case: %s)", binop.Op, describeMagicCase(tc))
		return false
	}

	return true
}

// checkNoFalsePositive verifies that non-magic patterns produce no matches.
//
// property: for all non-magic IR blocks: RecognizeMagicDivisors returns 0 matches
func checkNoFalsePositive(t *testing.T, tc *nonMagicCase) bool {
	t.Helper()

	x := u32Var("x", 1)
	y := u32Var("y", 1)

	// build a block with a single non-magic arithmetic operation
	block := &ir.BasicBlock{
		ID: 0,
		Instructions: []ir.IRInstruction{
			&ir.Assign{
				Dest: y,
				Source: &ir.BinaryOp{
					Op:    tc.op,
					Left:  varExpr(x),
					Right: u32Const(tc.constVal),
				},
			},
		},
	}

	matches, err := RecognizeMagicDivisors(block)
	if err != nil {
		t.Logf("RecognizeMagicDivisors error: %v (op=%v constVal=%d)", err, tc.op, tc.constVal)
		return false
	}

	if len(matches) != 0 {
		t.Logf("false positive: expected 0 matches for non-magic op %v constVal=%d, got %d",
			tc.op, tc.constVal, len(matches))
		return false
	}

	// block must be unmodified
	if len(block.Instructions) != 1 {
		t.Logf("block was modified despite no match: expected 1 instruction, got %d", len(block.Instructions))
		return false
	}

	return true
}

// checkMultiPatternRecognition verifies that all magic divisor patterns in a block
// are recognized and the block is correctly rewritten.
//
// property: for a block with N magic patterns:
//   - RecognizeMagicDivisors returns exactly N matches
//   - block is rewritten to N division instructions (2N → N)
//   - each match has the correct divisor
func checkMultiPatternRecognition(t *testing.T, tc *multiMagicCase) bool {
	t.Helper()

	block := buildMultiMagicBlock(tc.cases)
	originalLen := len(block.Instructions) // 2 * len(cases)
	expectedMatches := len(tc.cases)

	matches, err := RecognizeMagicDivisors(block)
	if err != nil {
		t.Logf("RecognizeMagicDivisors error: %v", err)
		return false
	}

	if len(matches) != expectedMatches {
		t.Logf("expected %d matches, got %d (cases: %s)",
			expectedMatches, len(matches), describeMultiCase(tc))
		return false
	}

	// block must shrink by N (N multiplies removed)
	expectedLen := originalLen - expectedMatches
	if len(block.Instructions) != expectedLen {
		t.Logf("expected %d instructions after rewrite, got %d (cases: %s)",
			expectedLen, len(block.Instructions), describeMultiCase(tc))
		return false
	}

	// all remaining instructions must be division operations
	for i, instr := range block.Instructions {
		assign, ok := instr.(*ir.Assign)
		if !ok {
			t.Logf("instruction %d: expected *ir.Assign, got %T", i, instr)
			return false
		}
		binop, ok := assign.Source.(*ir.BinaryOp)
		if !ok {
			t.Logf("instruction %d: expected *ir.BinaryOp source, got %T", i, assign.Source)
			return false
		}
		if binop.Op != ir.BinOpUDiv && binop.Op != ir.BinOpDiv {
			t.Logf("instruction %d: expected division op, got %v", i, binop.Op)
			return false
		}
	}

	// build a set of expected divisors for cross-checking
	expectedDivisors := make(map[uint64]int)
	for _, c := range tc.cases {
		expectedDivisors[c.divisor]++
	}
	recoveredDivisors := make(map[uint64]int)
	for _, m := range matches {
		recoveredDivisors[m.Divisor]++
	}
	for d, count := range expectedDivisors {
		if recoveredDivisors[d] != count {
			t.Logf("divisor %d: expected %d occurrences, got %d (cases: %s)",
				d, count, recoveredDivisors[d], describeMultiCase(tc))
			return false
		}
	}

	return true
}

// ============================================================================
// IR block builders
// ============================================================================

// buildMagicBlockFromCase constructs a two-instruction basic block encoding
// the magic divisor pattern for the given test case.
//
// structure:
//
//	t1 = dividend * magic
//	result = t1 >> shift  (BinOpShr for unsigned, BinOpSar for signed)
func buildMagicBlockFromCase(tc *magicDivTestCase) *ir.BasicBlock {
	var dividend ir.Variable
	if tc.kind == MagicDivSigned {
		dividend = i32Var("x", 1)
	} else {
		dividend = u32Var("x", 1)
	}

	shiftOp := ir.BinOpShr
	if tc.kind == MagicDivSigned {
		shiftOp = ir.BinOpSar
	}

	return buildMagicBlock(dividend, tc.magic, tc.shift, shiftOp)
}

// buildMultiMagicBlock constructs a basic block with multiple magic divisor patterns.
// each pattern uses a distinct dividend variable (x_i) and result variable (r_i)
// to avoid variable name collisions in the def-index.
func buildMultiMagicBlock(cases []*magicDivTestCase) *ir.BasicBlock {
	instrs := make([]ir.IRInstruction, 0, len(cases)*2)

	for i, tc := range cases {
		// use distinct variable names per pattern to avoid def-index collisions
		dividend := u32Var(fmt.Sprintf("x%d", i), 1)
		t1 := u32Var(fmt.Sprintf("t%d", i), 1)
		result := u32Var(fmt.Sprintf("r%d", i), 1)

		shiftOp := ir.BinOpShr
		if tc.kind == MagicDivSigned {
			shiftOp = ir.BinOpSar
		}

		// mul instruction: t_i = x_i * magic
		instrs = append(instrs, &ir.Assign{
			Dest: t1,
			Source: &ir.BinaryOp{
				Op:    ir.BinOpMul,
				Left:  varExpr(dividend),
				Right: u32Const(tc.magic),
			},
		})

		// shift instruction: r_i = t_i >> shift
		instrs = append(instrs, &ir.Assign{
			Dest: result,
			Source: &ir.BinaryOp{
				Op:    shiftOp,
				Left:  varExpr(t1),
				Right: u32Const(uint64(tc.shift)),
			},
		})
	}

	return &ir.BasicBlock{
		ID:           0,
		Instructions: instrs,
	}
}

// ============================================================================
// description helpers for failure messages
// ============================================================================

// describeMagicCase returns a human-readable description of a magicDivTestCase.
func describeMagicCase(tc *magicDivTestCase) string {
	kindStr := "unsigned"
	if tc.kind == MagicDivSigned {
		kindStr = "signed"
	}
	return fmt.Sprintf("%s D=%d M=0x%x S=%d", kindStr, tc.divisor, tc.magic, tc.shift)
}

// describeMultiCase returns a human-readable description of a multiMagicCase.
func describeMultiCase(tc *multiMagicCase) string {
	s := fmt.Sprintf("%d patterns: ", len(tc.cases))
	for i, c := range tc.cases {
		if i > 0 {
			s += ", "
		}
		s += fmt.Sprintf("D=%d", c.divisor)
	}
	return s
}
