// Package typeinfer implements type inference using Hindley-Milner unification and MaxSMT.
// It generates type constraints from IR operations, performs ASI (Aggregate Structure Identification),
// and supports interprocedural type propagation with cyclic feedback to CFG builder.
package typeinfer

import (
	"fmt"

	"github.com/zarazaex69/sedec/pkg/ir"
)

// ConstraintKind classifies the semantic relationship between two type variables.
type ConstraintKind int

const (
	// ConstraintEquality asserts that two type variables must unify to the same type.
	// generated by assignments, phi-nodes, and copy operations.
	ConstraintEquality ConstraintKind = iota

	// ConstraintSubtype asserts that the left type is a subtype of the right type.
	// generated by implicit widening conversions and function argument passing.
	ConstraintSubtype

	// ConstraintFieldAccess asserts that the left type is a struct containing a field
	// at a specific byte offset with the right type.
	// generated by memory loads/stores with constant offsets from a base pointer.
	ConstraintFieldAccess

	// ConstraintPointerTo asserts that the left type is a pointer to the right type.
	// generated by load/store instructions and address-of operations.
	ConstraintPointerTo

	// ConstraintArrayElement asserts that the left type is an array whose element type
	// is the right type. generated by strided memory access patterns.
	ConstraintArrayElement

	// ConstraintReturnType asserts that the left type is the return type of a function
	// whose call result is the right type variable.
	ConstraintReturnType

	// ConstraintParamType asserts that the left type is the n-th parameter type of a
	// function call target. generated by call instructions.
	ConstraintParamType
)

// String returns a human-readable name for the constraint kind.
func (k ConstraintKind) String() string {
	const ptrKind = "ptr"
	switch k {
	case ConstraintEquality:
		return "eq"
	case ConstraintSubtype:
		return "sub"
	case ConstraintFieldAccess:
		return "field"
	case ConstraintPointerTo:
		return ptrKind
	case ConstraintArrayElement:
		return "array"
	case ConstraintReturnType:
		return "ret"
	case ConstraintParamType:
		return "param"
	default:
		return fmt.Sprintf("unknown(%d)", int(k))
	}
}

// TypeVar is a type variable identifier used in constraint solving.
// it corresponds to a specific IR variable or a synthetic node introduced
// during constraint generation (e.g., the pointee of a pointer).
type TypeVar struct {
	// Name is the canonical name of this type variable.
	// for IR variables: "<varname>_<version>", e.g. "rax_3"
	// for synthetic nodes: "$ptr_<id>", "$field_<id>", "$elem_<id>"
	Name string

	// Concrete holds a known concrete type if this variable is already resolved
	// (e.g., from a constant expression or relocation ground-truth axiom).
	// nil means the type is unknown and must be inferred.
	Concrete ir.Type
}

// String returns the type variable name, annotated with its concrete type if known.
func (tv TypeVar) String() string {
	if tv.Concrete != nil {
		return fmt.Sprintf("%s:%s", tv.Name, tv.Concrete.String())
	}
	return tv.Name
}

// TypeConstraint encodes a single type relationship between two type variables.
// the constraint solver (Hindley-Milner unification + MaxSMT) processes a set
// of these constraints to produce a TypeSolution.
type TypeConstraint struct {
	// Kind classifies the semantic relationship.
	Kind ConstraintKind

	// Left is the primary type variable (the "subject" of the constraint).
	Left TypeVar

	// Right is the secondary type variable (the "object" of the constraint).
	Right TypeVar

	// FieldOffset is the byte offset for ConstraintFieldAccess constraints.
	// zero for all other constraint kinds.
	FieldOffset int64

	// ParamIndex is the argument position for ConstraintParamType constraints (0-based).
	// zero for all other constraint kinds.
	ParamIndex int

	// Confidence is a weight in [0.0, 1.0] used by MaxSMT when constraints conflict.
	// relocation-derived axioms: 1.0
	// debug-info-derived:        0.9
	// calling-convention-derived: 0.8
	// operation-derived:         0.5
	// heuristic:                 0.3
	Confidence float64

	// Origin is a human-readable description of why this constraint was generated.
	// used for diagnostics and conflict reporting.
	Origin string
}

// String returns a compact human-readable representation of the constraint.
func (c TypeConstraint) String() string {
	switch c.Kind {
	case ConstraintFieldAccess:
		return fmt.Sprintf("%s.field[%d] eq %s (conf=%.2f, %s)",
			c.Left, c.FieldOffset, c.Right, c.Confidence, c.Origin)
	case ConstraintParamType:
		return fmt.Sprintf("%s param[%d] eq %s (conf=%.2f, %s)",
			c.Left, c.ParamIndex, c.Right, c.Confidence, c.Origin)
	case ConstraintEquality, ConstraintSubtype, ConstraintPointerTo,
		ConstraintArrayElement, ConstraintReturnType:
		return fmt.Sprintf("%s %s %s (conf=%.2f, %s)",
			c.Left, c.Kind, c.Right, c.Confidence, c.Origin)
	default:
		return fmt.Sprintf("%s %s %s (conf=%.2f, %s)",
			c.Left, c.Kind, c.Right, c.Confidence, c.Origin)
	}
}
